{"name": "test_post_new_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": ">   ???\nE   assert False\n\nC:\\Users\\Tamar Samara\\PycharmProjects\\swagerpytest\\testUser.py:36: AssertionError"}, "description": "\n    Check to add an existing user\n    failed\n    ", "attachments": [{"name": "log", "source": "1757c878-19dc-4e48-97bc-b9e59fe89c26-attachment.txt", "type": "text/plain"}], "start": 1660051403524, "stop": 1660051404218, "uuid": "87bdcf60-c9ad-4cf7-a487-b533523a0e54", "historyId": "68d9ea2b353713e44aacdc47c59cf8ea", "testCaseId": "a31a7ca7842c1566941aa796770c53e6", "fullName": "testUser#test_post_new_user", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "testUser"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testUser"}]}