{"name": "test_get_user_by_username_not_exists", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 200\n +  where 404 = <Response [404]>.status_code", "trace": ">   ???\nE   assert 404 == 200\nE    +  where 404 = <Response [404]>.status_code\n\nC:\\Users\\Tamar Samara\\PycharmProjects\\swagerpytest\\testUser.py:100: AssertionError"}, "description": "\n    Verify get user by username not found\n    failed\n    ", "attachments": [{"name": "log", "source": "cb8bb19d-191b-49d6-8287-53bdf3815938-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c79d13c3-2d1f-4ea6-b32d-cf18b5ae8b1c-attachment.txt", "type": "text/plain"}], "start": 1660051407389, "stop": 1660051408123, "uuid": "250b9c07-03a2-4f20-91dc-e110be13606c", "historyId": "18dcf4600cd4b4939437c2cdb7fc9583", "testCaseId": "805fe42b00894a5d98e6b14c94e03d30", "fullName": "testUser#test_get_user_by_username_not_exists", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "testUser"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testUser"}]}