{"name": "test_delete_order", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": ">   ???\nE   assert False\n\nC:\\Users\\Tamar Samara\\PycharmProjects\\swagerpytest\\testOrder.py:92: AssertionError"}, "description": "\n    Verify that the order has not been deleted by order ID not found\n    failed\n    ", "attachments": [{"name": "log", "source": "c7864a37-5393-441e-a9d5-eee509d69052-attachment.txt", "type": "text/plain"}], "start": 1660051432082, "stop": 1660051432975, "uuid": "5ed36cf6-1230-4aa6-b589-b04ea6f98a55", "historyId": "f39ef4a4a67176994b7d5c83cafcf56a", "testCaseId": "14e836105fcfda5368545f29627433b0", "fullName": "testOrder#test_delete_order", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "testOrder"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "14844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testOrder"}]}